# 1.1 - Numpy  (Numerical Python)

**[Documentación](https://numpy.org/doc/stable/)**

**[Código fuente](https://github.com/numpy/numpy)**


![numpy](images/numpy.png)

NumPy es el paquete fundamental para computación cientifíca en python. Es una librería de python nos permite manejar vectores, matrices, [tensores](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) (arrays multidimensionales) y además realizar todas las operaciones matemáticas y lógicas de los mismos, como la manipulación de la dimensión, ordenado, selección, I/O, operaciones estadísticas, transformadas de Fourier, simulación aleatoria y un largo etcétera. Constituye la herramienta de álgebra lineal.

## Recordatorio de álgebra

+ Contenidos:

    + Concepto de tensor
    + Operaciones con vectores
        + Concepto de espacio vectorial y base
        + Suma de vectores
        + Producto escalar
        + Producto vectorial
    + Operaciones con matrices
        + Suma de matrices
        + Producto matricial
        + Matriz Identidad
        + Matriz Traspuesta (Hermítica)
        + Matriz Inversa 
        + Determinate

### Tensor

La palabra ['tensor'](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) se utiliza a menudo como abreviatura de campo tensorial, que es un valor tensorial definido en cada punto en una variedad. El primero en utilizar esta palabra fue William Rowan Hamilton en 1846, empleándola para lo que actualmente se conoce como módulo y fue Woldemar Voigt en 1899 quien la empleó en su acepción actual. La palabra tensor proviene del latín tensus, participio pasado de tendere 'estirar, extender'. El nombre se extendió porque la teoría de la elasticidad fue una de las primeras aplicaciones físicas donde se usaron tensores. Gregorio Ricci-Curbastro en 1890 desarrolló la notación actual con el nombre de geometría diferencial absoluta, y se popularizó con la publicación de Cálculo Diferencial Absoluto de Tullio Levi-Civita en 1900. Con la introducción de la teoría de la relatividad general por parte de Albert Einstein alrededor de 1915 se encontró su aplicación más pragmática. La Relatividad General es netamente tensorial. Einstein había aprendido del mismo Levi-Civita el uso de tensores con gran dificultad.

Podemos pensar en un tensor como la generalización del ente algebraico. Con un ejemplo se verá más claro.

Un **número**, cualquier número, $2$, $3.6$, $\pi$, $\phi$, $\sqrt{2}$, es un **tensor de rango $0$**.

Un **vector**, cualquier vector, sea como sea su longitud, $(1, 2, 3)$, $(0, 5, 2, 1, 5)$, $(9,2)$, es un **tensor de rango $1$**.

Una **matriz**, cualquier matriz, sean cuales sean sus dimensiones, es un **tensor de rango $2$**.

Un **cubo de Rubik** por ejemplo es un **tensor de rango $3$**.

Pensar en dimensiones superiores es complicado por no decir imposible, pero se pueden interpretar a través del contenido. Una **bolsa llena de cubos de Rubik** es un **tensor de rango $4$**.

Una **caja llena de bolsas que están llenas de cubos de Rubik es un tensor de rango $5$**.

Y así sucesivamente.

### Operaciones con vectores

**Espacio vectorial**

La definición matemática de [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) implica los conceptos de conjunto, ley de composición(operación) interna y ley de composición externa, definida sobre un segundo conjunto. Resumiendo, un espacio vectorial es una estructura creada sobre un conjunto no vacío con ambas leyes de composición. A los elementos de un espacio vectorial se les llama vectores.

Veamos un ejemplo:

Un espacio vectorial es el espacio tridimensional ${\Bbb R}^{3}$. Los elementos de ${\Bbb R}^{3}$ son vectores, por lo que la ley de composición interna es la suma de vectores. Para la ley de composición externa se necesita otro conjunto, que en esta caso son los números reales ${\Bbb R}$, y queda definida como el producto por escalares, multiplicar un vector por un número.



**Base vectorial**

Una [base](https://es.wikipedia.org/wiki/Base_(%C3%A1lgebra)) es un conjunto de vectores {$v_{1}, v_{2}, v_{3}, ... ,v_{n}$} que cumplen las siguientes propiedades:

+ Todos los elementos de la base pertenecen al mismo espacio vectorial.
+ Los elementos de la base forman un sistema linealmente independiente (ninguno es combinación lineal de los demás).
+ Cualquier elemento del espacio vectorial se puede escribir como combinación lineal de los elementos de la base (es lo que se llama sistema generador del espacio vectorial).

Ejemplo:

En ${\Bbb R}^{3}$, la base principal (llamada canónica) es {$(1,0,0), (0,1,0), (0,0,1)$}. Todos esos vectores pertenecen a ${\Bbb R}^{3}$, son linealmente independientes(ninguno puede ser una suma de los otros) y cualquier otro vector en ${\Bbb R}^{3}$ se puede representar como una suma de esos tres, una combinación lineal. No es única, otra base de ${\Bbb R}^{3}$ podría ser {$(1,1,1), (1,1,0), (1,0,0)$}



**Suma de vectores**

Los vectores se suman por componentes, lo que implica que ambos tienen la misma longitud. Por ejemplo en ${\Bbb R}^{3}$:

$$\vec{A}=A_{x}\vec{i}+A_{y}\vec{j}+A_{z}\vec{k}$$

$$\vec{B}=B_{x}\vec{i}+B_{y}\vec{j}+B_{z}\vec{k}$$

$$\vec{A}+\vec{B}=(B_{x}+A_{x})\vec{i}+(B_{y}+A_{y})\vec{j}+(B_{z}+A_{z})\vec{k}$$

$$$$

$$\vec{A}=(1,8,9)$$

$$\vec{B}=(4,3,0)$$

$$\vec{A}+\vec{B}=(5,11,9)$$



**Producto escalar**

Hay que diferenciar entre producto por escalares, un número por un vector resultando un vector, y el productor escalar donde se multiplican dos vectores resultando un número, un escalar.

+ Producto por escalares:

Se realiza elemento a elemento la multiplicación por el número:

$$\vec{A}=(1,8,9)$$

$$2*\vec{A}=(2,16,18)$$

+ Productos escalar:

Se realiza multiplicando elemento un vector fila por un vector columna y sumando los resultados. Hay que tener en cuenta, igual que en la suma, que ambos vectores tienen el mismo número de elementos. También se le llama producto punto (dot product) o producto interno (inner product).

$$\vec{A}\cdot\vec{B}=(1, 8, 9)\cdot\begin{pmatrix}4\\3\\0\end{pmatrix} = 1·4+8·3+9·0 = 4+24+0 = 28$$



**Producto vectorial**

En este caso, se multiplican dos vectores resultando otro vector. La manera más fácil de hacerlo es a través de un determinante:


$$\vec{A}\times \vec{B} = \begin{vmatrix}
\hat{\imath}&\hat{\jmath}&\hat{k}\\
1 & 8 & 9 \\
4 & 3 & 0
\end{vmatrix} = \begin{vmatrix}
8 & 9 \\
3 & 0
\end{vmatrix}·\hat{\imath} - 
\begin{vmatrix}
1 & 9 \\
4 & 0
\end{vmatrix}·\hat{\jmath} +
\begin{vmatrix}
1 & 8 \\
4 & 3
\end{vmatrix}·\hat{k} = (8·0-9·3)·\hat{\imath}-(1·0-9·4)·\hat{\jmath}+(1·3-8·4)·\hat{k}$$

$$\vec{A}\times \vec{B} = (-27, 36, -29)$$

### Operaciones con matrices


**Suma de matrices**

Las matrices tienen definidas sus dimensiones sugún el número de filas($m$) y de columnas($n$), y se representan como $A_{mxn}$. Para sumar matrices las dimensiones tienen que ser las mismas, igual que ocurría con los vectores, y se realiza elemento a elemento (element wise):


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}+\begin{pmatrix}
0 & 0 & 3 \\
2 & 2 & 7 
\end{pmatrix}=\begin{pmatrix}
5 & 7 & 4 \\
6 & 2 & 9 
\end{pmatrix}$$



**Producto matricial**

Para multiplicar matrices tenemos que tener en cuenta las dimensiones, porque el producto matricial no es conmutativo e incluso a veces no se puede realizar. El número de columnas de la primera matriz tiene que ser igual que el número de filas de la segunda y el resultado tendrá el número de filas de la primera y el número de columnas de la segunda. Es decir:

$$A_{rxn}\cdot B_{nxq} = C_{rxq}$$


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}\cdot\begin{pmatrix}
0 & 0 \\
2 & 3 \\
2 & 7 
\end{pmatrix}=\begin{pmatrix}
5·0+7·2+1·2 & 5·0+7·3+1·7 \\
4·0+0·2+2·2 & 4·0+0·3+2·7
\end{pmatrix}=\begin{pmatrix}
18 & 28 \\
4 & 14
\end{pmatrix}$$



**Matriz Identidad**

Elemento neutro de la multiplicación, solo $1_s$ en la diagonal:

$$I = \begin{pmatrix}
1&0&\cdots&0&0\\
0&1&\cdots&0&0\\
\vdots&\vdots&\ddots&\vdots&\vdots\\
0&\cdots&\cdots&\cdots&0\\
0&0&\cdots&1&0\\
0&0&\cdots&0&1\\
\end{pmatrix}$$



**Matriz traspuesta  (hermítica)**

La traspuesta $A^{T}$ de una matriz $A$ puede ser obtenida reflejando los elementos a lo largo de su diagonal.

$$A=\begin{pmatrix}
5 & 7 & 9 \\
4 & 0 & 7 \\
1 & 2 & 2
\end{pmatrix}$$

$$A^{T}=\begin{pmatrix}
5 & 4 & 1 \\
7 & 0 & 2 \\
9 & 7 & 2
\end{pmatrix}$$


Se le dice hermítica si los elementos son números complejos, es la traspuesta conjugada (el conjugado de $x+iy$ es $x-iy$).


**Matriz Inversa**

¿Como se dividen las matrices? Se multiplica por la inversa. El cálculo de la matriz inversa es:

$$A= \begin{pmatrix}
       a_{11} & a_{12} \\ 
       a_{21} & a_{22}
    \end{pmatrix}$$
    
    
$$A^{-1}=\begin{pmatrix}
a_{11} & a_{12} \\ 
a_{21} & a_{22}
\end{pmatrix}^{-1}
=\frac{1}{\lvert A\rvert}
\begin{pmatrix}
a_{22} & -a_{12} \\ 
-a_{21} &  a_{11}
\end{pmatrix}$$


**Determinante**

$$A=\begin{pmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{pmatrix}$$
  

$$$$


$$det(A)=\begin{vmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 0 & 0 \\ 
    -2 & 1 & 0 \\ 
    -2 & 0 & 1
  \end{vmatrix}\cdot
  \begin{vmatrix}
    1 & 4 & 1 \\ 
    2 & 6 & 3 \\ 
    2 & 10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 4 & 1 \\ 
    0 & -2 & 1 \\ 
    0 & 2 & 1
  \end{vmatrix}
  =
  \begin{vmatrix}
    -2 & 1 \\ 
    2 & 1
  \end{vmatrix}
  =-4$$
  
  

**Veamos algo de todo esto en python:**


**Arrays**

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# numero aleatorio

np.random.random(1)

array([0.32494622])

In [4]:
type(np.random.random(1))

numpy.ndarray

In [5]:
type(np.random.random(1)[0])

numpy.float64

In [6]:
# vector

vector=np.random.random(5) # nos alea uniformente distribuidos

vector

array([0.59881097, 0.89122354, 0.91414188, 0.39283257, 0.32230589])

In [7]:
type(vector)

numpy.ndarray

In [8]:
2 * [1, 2, 3, 4]

[1, 2, 3, 4, 1, 2, 3, 4]

In [9]:
2 * vector

array([1.19762193, 1.78244709, 1.82828377, 0.78566514, 0.64461177])

In [10]:
# matriz

matriz=np.random.random((10, 4))

matriz

array([[0.34408505, 0.80128451, 0.66636761, 0.95011864],
       [0.57136556, 0.3594123 , 0.60933257, 0.66157438],
       [0.40008157, 0.15418789, 0.85280935, 0.73980336],
       [0.41883929, 0.25168955, 0.99692579, 0.10554478],
       [0.91610893, 0.59346241, 0.11225704, 0.72798686],
       [0.17160036, 0.58775366, 0.13446078, 0.94017594],
       [0.74059127, 0.68900467, 0.5485582 , 0.10700344],
       [0.53680047, 0.34983769, 0.71594224, 0.50485326],
       [0.77586621, 0.70384722, 0.09399116, 0.07529197],
       [0.55751449, 0.34453479, 0.70146522, 0.6713267 ]])

In [11]:
type(matriz)

numpy.ndarray

In [12]:
matriz.shape

(10, 4)

In [13]:
matriz.size

40

In [14]:
len(matriz)

10

In [15]:
matriz[0]   # 1a fila

array([0.34408505, 0.80128451, 0.66636761, 0.95011864])

In [16]:
matriz[0][-1]

0.9501186374677855

**slicing**

los `:` signican todo, es decir, todas las filas. Luego, separado por coma, el 0, primer elemento de cada fila, es decir, la primera columna

In [17]:
matriz[:, 0]    #1ª columna

array([0.34408505, 0.57136556, 0.40008157, 0.41883929, 0.91610893,
       0.17160036, 0.74059127, 0.53680047, 0.77586621, 0.55751449])

In [18]:
matriz[0, 0]

0.34408505308334714

In [19]:
matriz[0][0]

0.34408505308334714

In [20]:
lst=[1, 2, 3]

type(lst)

list

In [21]:
array=np.array(lst)

type(array)

numpy.ndarray

In [22]:
type(list(array))

list

In [23]:
array.shape

(3,)

In [24]:
lst.shape

AttributeError: 'list' object has no attribute 'shape'

In [25]:
# cubo, tensor rango 3

cubo=np.random.random((3, 3, 2))

cubo

array([[[0.42623807, 0.63228989],
        [0.67029847, 0.23553809],
        [0.96060611, 0.3668177 ]],

       [[0.04394093, 0.58580372],
        [0.23069882, 0.53333053],
        [0.32896467, 0.02280469]],

       [[0.94993661, 0.54441567],
        [0.67401812, 0.27545636],
        [0.82134984, 0.24904745]]])

In [26]:
# tensor rango 4

tensor=np.random.random((2, 3, 4, 5))

tensor

array([[[[0.54121083, 0.3066345 , 0.26478979, 0.48161674, 0.54529541],
         [0.93713938, 0.14433024, 0.53946114, 0.79643921, 0.38250675],
         [0.57550426, 0.66746298, 0.54669526, 0.49793577, 0.14687616],
         [0.94360269, 0.47211322, 0.2038589 , 0.46055436, 0.73789853]],

        [[0.366953  , 0.86514861, 0.78955474, 0.82088197, 0.40451274],
         [0.52261386, 0.48893859, 0.21890617, 0.38194145, 0.04592856],
         [0.04122369, 0.39367418, 0.46088667, 0.35337927, 0.49283345],
         [0.75535101, 0.92878047, 0.00563487, 0.29610837, 0.02204542]],

        [[0.64931012, 0.92809919, 0.68176778, 0.10405548, 0.21260931],
         [0.34848819, 0.77135809, 0.03855581, 0.35904293, 0.32414476],
         [0.4918454 , 0.13263862, 0.62610073, 0.6318085 , 0.26283061],
         [0.51899844, 0.8723194 , 0.76879922, 0.02312825, 0.09586578]]],


       [[[0.14231032, 0.75515365, 0.59216009, 0.9812427 , 0.42030329],
         [0.70165839, 0.47687693, 0.94261716, 0.39985795, 0.94780273]

In [27]:
tensor.shape

(2, 3, 4, 5)

In [28]:
tensor[0][0][:, 0][-1]

0.9436026900193708

**Operaciones matemáticas**

In [29]:
matriz

array([[0.34408505, 0.80128451, 0.66636761, 0.95011864],
       [0.57136556, 0.3594123 , 0.60933257, 0.66157438],
       [0.40008157, 0.15418789, 0.85280935, 0.73980336],
       [0.41883929, 0.25168955, 0.99692579, 0.10554478],
       [0.91610893, 0.59346241, 0.11225704, 0.72798686],
       [0.17160036, 0.58775366, 0.13446078, 0.94017594],
       [0.74059127, 0.68900467, 0.5485582 , 0.10700344],
       [0.53680047, 0.34983769, 0.71594224, 0.50485326],
       [0.77586621, 0.70384722, 0.09399116, 0.07529197],
       [0.55751449, 0.34453479, 0.70146522, 0.6713267 ]])

In [30]:
matriz.sum()

21.18365719436963

In [31]:
matriz.sum(axis=0)    # suma por columnas

array([5.4328532 , 4.83501469, 5.43210997, 5.48367934])

In [32]:
matriz.sum(axis=1)    # suma por filas

array([2.76185582, 2.20168482, 2.14688217, 1.77299942, 2.34981524,
       1.83399074, 2.08515759, 2.10743365, 1.64899655, 2.2748412 ])

In [33]:
matriz.sum(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [34]:
cubo.sum(axis=2)

array([[1.05852796, 0.90583656, 1.32742381],
       [0.62974464, 0.76402935, 0.35176937],
       [1.49435228, 0.94947449, 1.07039729]])

In [35]:
matriz[:, 2].sum()

5.43210996827078

In [36]:
sum(matriz[:, 2])

5.43210996827078

In [37]:
matriz[0].sum()

2.7618558162907973

In [38]:
tensor.shape

(2, 3, 4, 5)

In [39]:
tensor.sum(axis=0).shape     # suma por cubos

(3, 4, 5)

In [40]:
tensor.sum(axis=1).shape     # suma por capas del cubo

(2, 4, 5)

In [41]:
tensor.sum(axis=2).shape     # suma por filas

(2, 3, 5)

In [42]:
tensor.sum(axis=3).shape     # suma por columnas

(2, 3, 4)

In [43]:
matriz.min()

0.07529196826080709

In [44]:
matriz.max()

0.9969257929714879

In [45]:
matriz[0:2, 0:2].max()

0.8012845131147897

In [46]:
matriz.max(axis=1)

array([0.95011864, 0.66157438, 0.85280935, 0.99692579, 0.91610893,
       0.94017594, 0.74059127, 0.71594224, 0.77586621, 0.70146522])

In [47]:
lst.index(2)

1

In [48]:
#help(np.where)

In [49]:
matriz.mean()

0.5295914298592408

In [50]:
matriz.mean(axis=0)

array([0.54328532, 0.48350147, 0.543211  , 0.54836793])

In [51]:
matriz.std(axis=1)

array([0.2237525 , 0.11483537, 0.27665692, 0.33833895, 0.29732633,
       0.33016323, 0.2492981 , 0.13006931, 0.32866209, 0.14011959])

In [52]:
matriz.std()

0.26758045457707563

In [53]:
matriz.var() ** 0.5

0.26758045457707563

In [54]:
matriz.var()

0.07159929967167444

In [55]:
matriz[0:5:2, 0:2]

array([[0.34408505, 0.80128451],
       [0.40008157, 0.15418789],
       [0.91610893, 0.59346241]])

In [56]:
np.add(matriz[0], matriz[1])  # suma de vectores

array([0.91545061, 1.16069682, 1.27570018, 1.61169302])

In [57]:
np.subtract(matriz[0], matriz[1])  # restar de vectores

array([-0.22728051,  0.44187221,  0.05703504,  0.28854425])

In [58]:
np.prod(matriz)   # productorio

2.511501392189067e-15

In [59]:
1e2   # notacion cientifica

100.0

In [60]:
1e-3

0.001

In [61]:
np.multiply(matriz[0], matriz[1])  # producto elemento a elemento

array([0.19659835, 0.28799151, 0.40603949, 0.62857415])

In [62]:
matriz[0]

array([0.34408505, 0.80128451, 0.66636761, 0.95011864])

In [63]:
matriz[1]

array([0.57136556, 0.3594123 , 0.60933257, 0.66157438])

In [64]:
np.dot(matriz[0], matriz[1])  # producto escalar

1.5192035039846112

In [65]:
np.dot(matriz, matriz)

ValueError: shapes (10,4) and (10,4) not aligned: 4 (dim 1) != 10 (dim 0)

In [66]:
matriz.shape

(10, 4)

In [67]:
matriz.T.shape

(4, 10)

In [68]:
matriz.transpose().shape

(4, 10)

In [69]:
np.dot(matriz, matriz.T).shape

(10, 10)

In [70]:
np.matmul(matriz.T, matriz).shape

(4, 4)

In [71]:
np.matmul(matriz[0], matriz[1])

1.5192035039846112

In [72]:
np.cross(matriz[0][:3], matriz[1][:3])  # producto vectorial

array([ 0.24874803,  0.17107727, -0.33415797])

In [73]:
matriz[0][:3]

array([0.34408505, 0.80128451, 0.66636761])

In [74]:
matriz.cumsum()

array([ 0.34408505,  1.14536957,  1.81173718,  2.76185582,  3.33322138,
        3.69263368,  4.30196625,  4.96354063,  5.36362221,  5.5178101 ,
        6.37061944,  7.1104228 ,  7.5292621 ,  7.78095165,  8.77787744,
        8.88342222,  9.79953115, 10.39299356, 10.5052506 , 11.23323746,
       11.40483782, 11.99259148, 12.12705226, 13.06722821, 13.80781948,
       14.49682415, 15.04538235, 15.15238579, 15.68918626, 16.03902395,
       16.75496618, 17.25981944, 18.03568565, 18.73953287, 18.83352403,
       18.908816  , 19.46633048, 19.81086527, 20.51233049, 21.18365719])

In [75]:
np.tensordot(matriz, matriz)

array(14.08265529)

In [76]:
matriz.cumprod()

array([3.44085053e-01, 2.75710024e-01, 1.83724231e-01, 1.74559816e-01,
       9.97374669e-02, 3.58468727e-02, 2.18426671e-02, 1.44505490e-02,
       5.78139838e-03, 8.91421610e-04, 7.60212682e-04, 5.62407894e-04,
       2.35558526e-04, 5.92876202e-05, 5.91053578e-05, 6.23826207e-06,
       5.71492757e-06, 3.39159468e-06, 3.80730387e-07, 2.77166720e-07,
       4.75619083e-08, 2.79546857e-08, 3.75880888e-09, 3.53394168e-09,
       2.61720636e-09, 1.80326741e-09, 9.89197127e-10, 1.05847498e-10,
       5.68189865e-11, 1.98774228e-11, 1.42310865e-11, 7.18461041e-12,
       5.57429644e-12, 3.92345303e-12, 3.68769907e-13, 2.77654122e-14,
       1.54796195e-14, 5.33326737e-15, 3.74110158e-15, 2.51150139e-15])

In [77]:
np.nan

nan

In [78]:
type(np.nan)

float

In [79]:
type(None)

NoneType

In [80]:
np.inf

inf

In [81]:
type(np.inf)

float

In [82]:
np.pi

3.141592653589793

**Dimensiones**

In [83]:
matriz.shape

(10, 4)

In [84]:
matriz

array([[0.34408505, 0.80128451, 0.66636761, 0.95011864],
       [0.57136556, 0.3594123 , 0.60933257, 0.66157438],
       [0.40008157, 0.15418789, 0.85280935, 0.73980336],
       [0.41883929, 0.25168955, 0.99692579, 0.10554478],
       [0.91610893, 0.59346241, 0.11225704, 0.72798686],
       [0.17160036, 0.58775366, 0.13446078, 0.94017594],
       [0.74059127, 0.68900467, 0.5485582 , 0.10700344],
       [0.53680047, 0.34983769, 0.71594224, 0.50485326],
       [0.77586621, 0.70384722, 0.09399116, 0.07529197],
       [0.55751449, 0.34453479, 0.70146522, 0.6713267 ]])

In [85]:
matriz.reshape((5, 8))

array([[0.34408505, 0.80128451, 0.66636761, 0.95011864, 0.57136556,
        0.3594123 , 0.60933257, 0.66157438],
       [0.40008157, 0.15418789, 0.85280935, 0.73980336, 0.41883929,
        0.25168955, 0.99692579, 0.10554478],
       [0.91610893, 0.59346241, 0.11225704, 0.72798686, 0.17160036,
        0.58775366, 0.13446078, 0.94017594],
       [0.74059127, 0.68900467, 0.5485582 , 0.10700344, 0.53680047,
        0.34983769, 0.71594224, 0.50485326],
       [0.77586621, 0.70384722, 0.09399116, 0.07529197, 0.55751449,
        0.34453479, 0.70146522, 0.6713267 ]])

In [86]:
matriz.flatten().shape

(40,)

In [87]:
matriz

array([[0.34408505, 0.80128451, 0.66636761, 0.95011864],
       [0.57136556, 0.3594123 , 0.60933257, 0.66157438],
       [0.40008157, 0.15418789, 0.85280935, 0.73980336],
       [0.41883929, 0.25168955, 0.99692579, 0.10554478],
       [0.91610893, 0.59346241, 0.11225704, 0.72798686],
       [0.17160036, 0.58775366, 0.13446078, 0.94017594],
       [0.74059127, 0.68900467, 0.5485582 , 0.10700344],
       [0.53680047, 0.34983769, 0.71594224, 0.50485326],
       [0.77586621, 0.70384722, 0.09399116, 0.07529197],
       [0.55751449, 0.34453479, 0.70146522, 0.6713267 ]])

In [88]:
matriz + np.array([1, 2, 3, 4])

array([[1.34408505, 2.80128451, 3.66636761, 4.95011864],
       [1.57136556, 2.3594123 , 3.60933257, 4.66157438],
       [1.40008157, 2.15418789, 3.85280935, 4.73980336],
       [1.41883929, 2.25168955, 3.99692579, 4.10554478],
       [1.91610893, 2.59346241, 3.11225704, 4.72798686],
       [1.17160036, 2.58775366, 3.13446078, 4.94017594],
       [1.74059127, 2.68900467, 3.5485582 , 4.10700344],
       [1.53680047, 2.34983769, 3.71594224, 4.50485326],
       [1.77586621, 2.70384722, 3.09399116, 4.07529197],
       [1.55751449, 2.34453479, 3.70146522, 4.6713267 ]])

In [89]:
matriz + [1, 2, 3, 4]

array([[1.34408505, 2.80128451, 3.66636761, 4.95011864],
       [1.57136556, 2.3594123 , 3.60933257, 4.66157438],
       [1.40008157, 2.15418789, 3.85280935, 4.73980336],
       [1.41883929, 2.25168955, 3.99692579, 4.10554478],
       [1.91610893, 2.59346241, 3.11225704, 4.72798686],
       [1.17160036, 2.58775366, 3.13446078, 4.94017594],
       [1.74059127, 2.68900467, 3.5485582 , 4.10700344],
       [1.53680047, 2.34983769, 3.71594224, 4.50485326],
       [1.77586621, 2.70384722, 3.09399116, 4.07529197],
       [1.55751449, 2.34453479, 3.70146522, 4.6713267 ]])

In [90]:
vector + 10

array([10.59881097, 10.89122354, 10.91414188, 10.39283257, 10.32230589])

In [91]:
vector

array([0.59881097, 0.89122354, 0.91414188, 0.39283257, 0.32230589])

In [92]:
np.where(matriz > 0.5, 1, 0)

array([[0, 1, 1, 1],
       [1, 0, 1, 1],
       [0, 0, 1, 1],
       [0, 0, 1, 0],
       [1, 1, 0, 1],
       [0, 1, 0, 1],
       [1, 1, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 0, 1, 1]])

In [93]:
vector.dtype

dtype('float64')

In [94]:
a=np.where(matriz > 0.5, 'hola', 0)

a.dtype

dtype('<U21')

In [95]:
np.array(['hola', 'adios']).dtype

dtype('<U5')

In [96]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [97]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])